steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - asia-northeast1-docker.pkg.dev/youtube-radio-auto-487900/radio-shorts-repo/cloud-worker:latest
      - -f
      - Dockerfile.cloud_worker
      - .

images:
  - asia-northeast1-docker.pkg.dev/youtube-radio-auto-487900/radio-shorts-repo/cloud-worker:latest
